### ISSUE TITLE
Cannot wrap string value

### ISSUE THREAD

**Issue by shamsulhusainansari** [sanattaori/techdot#32]
deployedContract = VotingContract.new(['Sanat','Aniket','Mandar','Akshay'],{data: byteCode, from: web3.eth.accounts[0], gas: 4700000})
Uncaught:
Error: Cannot wrap string value "608060405234801561001057600080fd5b5060405161041d38038061041d833981018060405281019080805182019291905050508060019080519060200190610049929190610050565b50506100c8565b828054828255906000526020600020908101928215610092579160200282015b82811115610091578251829060001916905591602001919060010190610070565b5b50905061009f91906100a3565b5090565b6100c591905b808211156100c15760008160009055506001016100a9565b5090565b90565b610346806100d76000396000f30060806040526004361061006d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632f265cf714610072578063392e6678146100bd5780637021939f14610106578063b13c744b14610151578063cc9ab2671461019a575b600080fd5b34801561007e57600080fd5b506100a160048036038101908080356000191690602001909291905050506101cb565b604051808260ff1660ff16815260200191505060405180910390f35b3480156100c957600080fd5b506100ec6004803603810190808035600019169060200190929190505050610215565b604051808215151515815260200191505060405180910390f35b34801561011257600080fd5b506101356004803603810190808035600019169060200190929190505050610274565b604051808260ff1660ff16815260200191505060405180910390f35b34801561015d57600080fd5b5061017c60048036038101908080359060200190929190505050610294565b60405180826000191660001916815260200191505060405180910390f35b3480156101a657600080fd5b506101c960048036038101908080356000191690602001909291905050506102b7565b005b60008015156101d983610215565b151514156101e657600080fd5b600080836000191660001916815260200190815260200160002060009054906101000a900460ff169050919050565b600080600090505b60018054905081101561026957826000191660018281548110151561023e57fe5b906000526020600020015460001916141561025c576001915061026e565b808060010191505061021d565b600091505b50919050565b60006020528060005260406000206000915054906101000a900460ff1681565b6001818154811015156102a357fe5b906000526020600020016000915090505481565b600015156102c482610215565b151514156102d157600080fd5b6001600080836000191660001916815260200190815260200160002060008282829054906101000a900460ff160192506101000a81548160ff021916908360ff160217905550505600a165627a7a723058201df63b8ba65c70005c6a094b8409d12dc58001b824c1ec852cf1ae38b9c59dc600290000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000453616e6174000000000000000000000000000000000000000000000000000000416e696b657400000000000000000000000000000000000000000000000000004d616e6461720000000000000000000000000000000000000000000000000000416b736861790000000000000000000000000000000000000000000000000000" as a json-rpc type; strings must be prefixed with "0x".
    at Object.InvalidResponse (/home/shamsul/Videos/techdot-patch-1/node_modules/web3/lib/web3/errors.js:38:16)
    at RequestManager.send (/home/shamsul/Videos/techdot-patch-1/node_modules/web3/lib/web3/requestmanager.js:61:22)
    at Eth.send [as sendTransaction] (/home/shamsul/Videos/techdot-patch-1/node_modules/web3/lib/web3/method.js:145:58)
    at ContractFactory.new (/home/shamsul/Videos/techdot-patch-1/node_modules/web3/lib/web3/contract.js:228:33)
![Screenshot from 2022-12-16 21-51-30-1](https://user-images.githubusercontent.com/63342521/208143484-4fb1bc1f-8a78-46b3-9f59-2f5c84959da9.png)

**Comment by naimisha5gandham** [comment]
Did anyone got the solution for this issue??

**Comment by Sushantspatil** [comment]
add "0x+ bytecode" before the bytecode
