### ISSUE TITLE
JSON RPC Error after Submitting OTP

### ISSUE THREAD

**Issue by anilzapadiya94** [sanattaori/techdot#7]
Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (/home/anil/techdott/node_modules/web3/lib/web3/errors.js:38:16)
    at HttpProvider.send (/home/anil/techdott/node_modules/web3/lib/web3/httpprovider.js:91:22)
    at RequestManager.send (/home/anil/techdott/node_modules/web3/lib/web3/requestmanager.js:58:32)
    at Eth.get [as accounts] (/home/anil/techdott/node_modules/web3/lib/web3/property.js:107:62)
    at /home/anil/techdott/index.js:96:111
    at Layer.handle [as handle_request] (/home/anil/techdott/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/anil/techdott/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/anil/techdott/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/anil/techdott/node_modules/express/lib/router/layer.js:95:5)
    at /home/anil/techdott/node_modules/express/lib/router/index.js:281:22

**Comment by Krishna14K** [comment]
Bro need some clear guidance in running this project please help me out...i have emailed you respond soon..

**Comment by rahulgupta-G** [comment]
I was getting the same error

> Error: Invalid JSON RPC response: undefined
> at Object.InvalidResponse (/home/anil/techdott/node_modules/web3/lib/web3/errors.js:38:16)
> at HttpProvider.send (/home/anil/techdott/node_modules/web3/lib/web3/httpprovider.js:91:22)
> at RequestManager.send (/home/anil/techdott/node_modules/web3/lib/web3/requestmanager.js:58:32)
> at Eth.get [as accounts] (/home/anil/techdott/node_modules/web3/lib/web3/property.js:107:62)
> at /home/anil/techdott/index.js:96:111
> at Layer.handle [as handle_request] (/home/anil/techdott/node_modules/express/lib/router/layer.js:95:5)
> at next (/home/anil/techdott/node_modules/express/lib/router/route.js:137:13)
> at Route.dispatch (/home/anil/techdott/node_modules/express/lib/router/route.js:112:3)
> at Layer.handle [as handle_request] (/home/anil/techdott/node_modules/express/lib/router/layer.js:95:5)
> at /home/anil/techdott/node_modules/express/lib/router/index.js:281:22

I was getting the same error. Resolved this by running ganache-cli in a separate terminal and copying the first account address to the clist.js file as mentioned in the "Running the project" instructions already.
